config/routes.rb
Rails.application.routes.draw do
  resources :advertisments
  resources :variants
  resources :brands
  devise_for :users
  get 'home/index'

  root to: "home#index"
end

app/models/advertisment.rb
class Advertisment < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  belongs_to :variant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :brand
end

app/controllers/advertisments_controller.rb
class AdvertismentsController < ApplicationController
  before_action :set_advertisment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /advertisments
  # GET /advertisments.json
  def index
    @advertisments = Advertisment.all
    @variants = Variant.all
    @users = User.all
    @brands = Brand.all
  end

  # GET /advertisments/1
  # GET /advertisments/1.json
  def show
  end

  # GET /advertisments/new
  def new
    @advertisment = Advertisment.new
  end

  # GET /advertisments/1/edit
  def edit
  end

  # POST /advertisments
  # POST /advertisments.json
  def create
    @advertisment = Advertisment.new(advertisment_params)
    @advertisment.user_id = current_user.id
    respond_to do |format|
      if @advertisment.save
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully created.' }
        format.json { render :show, status: :created, location: @advertisment }
      else
        format.html { render :new }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisments/1
  # PATCH/PUT /advertisments/1.json
  def update
    respond_to do |format|
      if @advertisment.update(advertisment_params)
        format.html { redirect_to @advertisment, notice: 'Advertisment was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisment }
      else
        format.html { render :edit }
        format.json { render json: @advertisment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisments/1
  # DELETE /advertisments/1.json
  def destroy
    @advertisment.destroy
    respond_to do |format|
      format.html { redirect_to advertisments_url, notice: 'Advertisment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisment
      @advertisment = Advertisment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisment_params
      params.require(:advertisment).permit(:year, :kmdriven, :ownercount, :price, :color, :fueltype, :brand_id, :user_id, :variant_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
    @brands = Brand.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:model, :brand_id)
    end
end

app/helpers/advertisments_helper.rb
module AdvertismentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/advertisments/_form.html.erb
<%= form_with(model: advertisment, local: true) do |form| %>
  <% if advertisment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisment.errors.count, "error") %> prohibited this advertisment from being saved:</h2>

      <ul>
      <% advertisment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :advertisment_year %>
  </div>

  <div class="field">
    <%= form.label :kmdriven %>
    <%= form.text_field :kmdriven, id: :advertisment_kmdriven %>
  </div>

  <div class="field">
    <%= form.label :ownercount %>
    <%= form.number_field :ownercount, id: :advertisment_ownercount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :advertisment_price %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :advertisment_color %>
  </div>

  <div class="field">
    <%= form.label :fueltype %>
    <%= form.number_field :fueltype, id: :advertisment_fueltype %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.text_field :brand_id, id: :advertisment_brand_id %>
  </div>


  <div class="field">
    <%= form.label :variant_id %>
    <%= form.text_field :variant_id, id: :advertisment_variant_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advertisments/edit.html.erb
<h1>Editing Advertisment</h1>

<%= render 'form', advertisment: @advertisment %>

<%= link_to 'Show', @advertisment %> |
<%= link_to 'Back', advertisments_path %>

app/views/advertisments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertisments</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Kmdriven</th>
      <th>Ownercount</th>
      <th>Price</th>
      <th>Color</th>
      <th>Fueltype</th>
      <th>Brand</th>
      <th>User</th>
      <th>Variant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisments.each do |advertisment| %>
      <tr>
        <td><%= advertisment.year %></td>
        <td><%= advertisment.kmdriven %></td>
        <td><%= advertisment.ownercount %></td>
        <td><%= advertisment.price %></td>
        <td><%= advertisment.color %></td>
        <td><%= advertisment.fueltype %></td>
        <td><%= @brands.find(advertisment.brand_id).name %></td>
        <td><%= advertisment.user_id %></td>
        <td><%= @variants.find(advertisment.variant_id).model %></td>
        <td><%= link_to 'Show', advertisment %></td>
        <td><%= link_to 'Edit', edit_advertisment_path(advertisment) %></td>
        <td><%= link_to 'Destroy', advertisment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertisment', new_advertisment_path %>

app/views/advertisments/new.html.erb
<h1>New Advertisment</h1>

<%= render 'form', advertisment: @advertisment %>

<%= link_to 'Back', advertisments_path %>

app/views/advertisments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @advertisment.year %>
</p>

<p>
  <strong>Kmdriven:</strong>
  <%= @advertisment.kmdriven %>
</p>

<p>
  <strong>Ownercount:</strong>
  <%= @advertisment.ownercount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @advertisment.price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @advertisment.color %>
</p>

<p>
  <strong>Fueltype:</strong>
  <%= @advertisment.fueltype %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @advertisment.brand %>
</p>

<p>
  <strong>User:</strong>
  <%= @advertisment.user %>
</p>

<p>
  <strong>Variant:</strong>
  <%= @advertisment.variant %>
</p>

<%= link_to 'Edit', edit_advertisment_path(@advertisment) %> |
<%= link_to 'Back', advertisments_path %>

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brand_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <% if user_signed_in? %> 
    <div>Signed in as... <%= current_user.email %> 
    (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete%>)
    </div>
    <% else %>
    <%= link_to 'Register', new_user_registration_path %> or
    <%= link_to 'Sign in', new_user_session_path %> 
    <% end %>
  </body>
</html>

app/views/variants/_form.html.erb
<%= form_with(model: variant, local: true) do |form| %>
  <% if variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% variant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :variant_model %>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.text_field :brand_id, id: :variant_brand_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variants/edit.html.erb
<h1>Editing Variant</h1>

<%= render 'form', variant: @variant %>

<%= link_to 'Show', @variant %> |
<%= link_to 'Back', variants_path %>

app/views/variants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variants</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        
        <td><%= variant.model %></td>
        <td><%= @brands.find(variant.brand_id).name %></td>
        <td><%= link_to 'Show', variant %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant', new_variant_path %>

app/views/variants/new.html.erb
<h1>New Variant</h1>

<%= render 'form', variant: @variant %>

<%= link_to 'Back', variants_path %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @variant.model %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @variant.brand %>
</p>

<%= link_to 'Edit', edit_variant_path(@variant) %> |
<%= link_to 'Back', variants_path %>